sudo: false

language: node_js
services: mongodb
node_js: 4.4.5

before_install:
- curl https://install.meteor.com | /bin/sh
- export PATH="$HOME/.meteor:$PATH"
- npm install -g spacejam
- meteor --version
- make decrypt

script: make test
