language: node_js
node_js:
  - "0.10"
before_install:
  - "curl -L http://git.io/3l-rRA | /bin/sh"
  - "npm install velocity-cli -g"
services:
  - mongodb
script:
  - cd app && velocity test-app --ci --port 6969
