sudo: required
language: node_js
node_js:
  - "0.10"
before_install:
  - "curl -L https://raw.githubusercontent.com/sf-wind/meteor-velocity-travis-ci/master/configure.sh | /bin/sh"
services:
  - mongodb
script:
  - cd app && velocity test-app --ci --port 6969
